### ISSUE TITLE
Error al modificar creadores del arqueo

### ISSUE THREAD

**Issue by alevilar** [ristorantino/cash#2]
Al modificar Creador en arqueo me aparecen algunos errores y no me listan los usuarios del comercio correctramente. 
En este caso tenia 3 usuarios genericos (mozo, cajero y encargado) y 2 usuarios normales (contando al mio y a uno que estaba con el rol cocinero)

Además, modificar texto "lista de usuarios" del option "empty" para que sea el texto: "Seleccione", el "lista de usarios" podria ser utilizado como label
![image](https://cloud.githubusercontent.com/assets/222193/23733901/3bd98a6e-045a-11e7-8a09-1f96ca078b44.png)

**Comment by gonzaabel** [comment]
Fixed.
